<script setup lang="ts">
const password = ref("");
const isPasswordWrong = ref(false);

watch(password, () => {
  isPasswordWrong.value = false;
});

async function action() {
  await api("/users/me/password/verify", {
    method: "POST",
    body: { password: password.value },

    onApiError: {
      USER_CREDENTIALS_WRONG: () => {
        isPasswordWrong.value = true;
      },
    },
  });

  return { password: password.value };
}
</script>

<template>
  <Dialog size="medium" :action>
    <template #heading>Enable 2FA</template>

    <p>
      Secure your account against stolen passwords by enabling 2-factor
      authentication (2FA). A one-time code generated by a mobile app will be
      required in addition to your password when signing in.
    </p>

    <InputText
      v-model="password"
      label="Verify Current Password"
      type="password"
      maxlength="256"
      required
      :custom-validity="isPasswordWrong ? 'Incorrect password.' : ''"
    />

    <template #actions="{ cancel }">
      <Button type="submit">2FA Setup</Button>
      <Button @click="cancel">Cancel</Button>
    </template>
  </Dialog>
</template>
