<script setup lang="ts">
import { base32 } from "rfc4648";

const { email, password } = defineProps<{
  /** The user's email. */
  email: string;

  /** The user's password. */
  password: string;
}>();

// RFC 4226 (section 4) recommends TOTP secrets be 160 bits.
const secretBytes = crypto.getRandomValues(new Uint8Array(160 / 8));
const secret = base32.stringify(secretBytes);

const otpauthUri = computed(() => {
  const issuer = encodeURIComponent("File Garden");
  const accountName = encodeURIComponent(email);

  return `otpauth://totp/${issuer}:${accountName}?secret=${secret}&issuer=${issuer}`;
});

const otp = ref("");
const isOtpWrong = ref(false);

watch(otp, () => {
  isOtpWrong.value = false;
});

function action() {
  return api<{ backupCodes: string[] }>("/users/me/totp", {
    method: "POST",
    body: {
      credentials: { password },
      secret,
      otp: otp.value,
    },

    onApiError: {
      TOTP_SETUP_WRONG: () => {
        isOtpWrong.value = true;
      },
    },
  });
}
</script>

<template>
  <Dialog class="dialog-totp-setup" size="medium" :action>
    <template #heading>2FA Setup</template>

    <section>
      <!--
        The ARIA APG recommends that long dialogs auto-focus a static element at
        the start instead of applying `aria-describedby`.
      -->
      <!-- @vue-expect-error It falsely thinks `autofocus` isn't an attribute. -->
      <h2 class="step-heading" tabindex="-1" autofocus>
        <span class="step-numbering">1.</span>
        Install an authenticator app
      </h2>

      <p>
        Install any authenticator app on your mobile device. We recommend
        <A href="https://ente.io/auth/" target="_blank">Ente Auth</A>.
      </p>
    </section>

    <hr />

    <section>
      <h2 class="step-heading">
        <span class="step-numbering">2.</span>
        Scan the QR code
      </h2>

      <div class="totp-setup-step-qr-code">
        <div class="totp-setup-qr-code-wrapper">
          <QrCode :data="otpauthUri" />
        </div>

        <div class="totp-setup-qr-code-info">
          <p>Open your authenticator app, and use it to scan this image.</p>

          <p>
            Can't scan the image? Manually enter this secret key into the app:

            <code class="totp-setup-secret">
              {{
                secret
                  .toLowerCase()
                  .replace(/(.{4})/g, "$1 ")
                  .trimEnd()
              }}
            </code>
          </p>
        </div>
      </div>
    </section>

    <hr />

    <section>
      <h2 class="step-heading">
        <span class="step-numbering">3.</span>
        Verify your 2FA code
      </h2>

      <p>
        Enter the 6-digit code generated by your authenticator app to confirm
        your 2FA is set up correctly.
      </p>

      <InputOneTimeCode
        v-model="otp"
        label="2FA Code"
        allow="numeric"
        required
        :custom-validity="isOtpWrong ? 'Incorrect 2FA code.' : ''"
      />
    </section>

    <template #actions="{ cancel }">
      <Button type="submit">Enable 2FA</Button>
      <Button @click="cancel">Cancel</Button>
    </template>
  </Dialog>
</template>

<style scoped lang="scss">
:global(.dialog-totp-setup h2) {
  color: var(--color-text-weaker);
}

.step-heading {
  font-size: 1.5em;
}

.step-numbering::after {
  content: "\00a0";
}

.totp-setup-step-qr-code {
  display: flex;
  flex-wrap: wrap;
  gap: 1.25em;
}

.totp-setup-qr-code-wrapper {
  display: flex;
  align-items: center;
}

.totp-setup-qr-code-info {
  flex-grow: 1;
  min-width: 50%;
  width: 0;
}

.totp-setup-secret {
  display: block;
  margin-top: 0.25em;

  color: var(--color-text-weak);
}
</style>
